name: rAFK-Chat
version: 1.0
main: com.afk.Main
api-version: '1.21'
author: rilkay

commands:
  rafk:
    permission: rilkayafk.reload
    usage: /<command> reload

permissions:
  rilkayafk.reload:
    default: op